version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3309:3306'
    volumes:
      - db:/var/lib/mysql
  redis-cache:
    image: redis
    container_name: redis-cache
    ports:
      - "7000:6379"
    command: redis-server --requirepass "Password@123"
networks:
  default:
    name: spring
volumes:
  db: